AWSTemplateFormatVersion: "2010-09-09"
Description: "Converting file to csv to parquet using aws glue"
Parameters:
  CrawlerName:
    Type: String
    Default: crawler-test-11
  DatabaseName:
    Type: String
    Default: database-test-1
  InputTableName1:
    Type: String
    Default: cfn-manual-table-test-1
  DataBucketName:
    Type: String
    Description: "Name of the S3 bucket in which the Csv file  will be uploaded."
  JobName:
    Type: String
    Default: job-S3-to-S3-2

Resources:
  AwsGlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        PolicyName: root
        PolicyDocument:
          Version: 2012-10-17
          Statement:
                - Effect: Allow
                  Action:
                    - "s3:GetObject"
                    - "s3:PutObject"
                    - "s3:ListBucket"
                    - "s3:DeleteObject"
                  Resource:
                    - !Sub "arn:aws:s3:::${DataBucketName}"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
  DataBase:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
          Name: !Ref DatabaseName
          Description: "Database to hold tables for data"
  Table1:

    DependsOn: DataBase
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref DatabaseName
      TableInput:
        Name: !Ref InputTableName1
        Description: "Define the first few columns of the flights table"
        TableType: EXTERNAL_TABLE
        Parameters: {
        "classification": "csv"
        }

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref CrawlerName
      Role: !GetAtt AwsGlueJobRole.Arn
      Description: AWS Glue crawler to crawl File data
      DatabaseName: !Ref DatabaseName
      Targets:
        S3Targets:
          - Path: "s3://crawler-public-us-east-1/flight/2016/csv"
      TablePrefix: !Ref InputTableName1

  EtLJob1:
    Type: AWS::Glue::Job
    Properties:
      Role: !Ref AwsGlueJobRole
      Name: !Ref JobName
      Command:
        Name: gluet1
        ScriptLocation: s3://aws-glue-scripts-123456789012-ap-south-1/Write/sal-job-test2
